config:
  aws:region: eu-west-1
  aws:profile: inmo
  results-api:lambda_memory_mb: "256"
  results-api:lambda_timeout_seconds: "10"
encryptionsalt: v1:7pJBnEqaQNE=:v1:kfokHPfWwJgvIfAf:DTjHZXGfNuoSl0FMxs8oVa3J7KLuRg==
