config:
  aws:region: eu-west-1
  aws:profile: inmo
  vector-query:lambda_memory_mb: "1024"
  vector-query:lambda_timeout_seconds: "60"
  vector-query:batch_size: "1"
encryptionsalt: v1:xUd2HzK8I4w=:v1:InmA9Uq3t3GiKANI:Iz5hyPY7+am6Ea6zUeIhpLiBmvR4fw==
