# Filtering and ranking
ROOMS_RELAXATION_COEFFICIENT = 1  # unit
BATHROOMS_RELAXATION_COEFFICIENT = 1  # unit
SURFACE_RELAXATION_COEFFICIENT = 0.15  # percentage
PRICE_RELAXATION_COEFFICIENT = 0.10  # percentage
